// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// BTF
Rcpp::List BTF(Rcpp::List& TensorList, Rcpp::NumericVector& MatrixType, Rcpp::NumericMatrix& U0, Rcpp::NumericMatrix& V0, Rcpp::List& R0, Rcpp::NumericVector& SS0, Rcpp::NumericVector& Mu0, int S, SEXP SaveDir, int Thin, int Burn, int Start);
RcppExport SEXP _BTF_BTF(SEXP TensorListSEXP, SEXP MatrixTypeSEXP, SEXP U0SEXP, SEXP V0SEXP, SEXP R0SEXP, SEXP SS0SEXP, SEXP Mu0SEXP, SEXP SSEXP, SEXP SaveDirSEXP, SEXP ThinSEXP, SEXP BurnSEXP, SEXP StartSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type TensorList(TensorListSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type MatrixType(MatrixTypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type U0(U0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type V0(V0SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type SS0(SS0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type Mu0(Mu0SEXP);
    Rcpp::traits::input_parameter< int >::type S(SSEXP);
    Rcpp::traits::input_parameter< SEXP >::type SaveDir(SaveDirSEXP);
    Rcpp::traits::input_parameter< int >::type Thin(ThinSEXP);
    Rcpp::traits::input_parameter< int >::type Burn(BurnSEXP);
    Rcpp::traits::input_parameter< int >::type Start(StartSEXP);
    rcpp_result_gen = Rcpp::wrap(BTF(TensorList, MatrixType, U0, V0, R0, SS0, Mu0, S, SaveDir, Thin, Burn, Start));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fabp_lin_reg
Rcpp::List rcpp_fabp_lin_reg(Rcpp::NumericVector& Y0, double& S0, Rcpp::NumericVector& R0, Rcpp::NumericMatrix& U0, Rcpp::NumericMatrix& V0);
RcppExport SEXP _BTF_rcpp_fabp_lin_reg(SEXP Y0SEXP, SEXP S0SEXP, SEXP R0SEXP, SEXP U0SEXP, SEXP V0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type Y0(Y0SEXP);
    Rcpp::traits::input_parameter< double& >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type R0(R0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type U0(U0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type V0(V0SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fabp_lin_reg(Y0, S0, R0, U0, V0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BTF_BTF", (DL_FUNC) &_BTF_BTF, 12},
    {"_BTF_rcpp_fabp_lin_reg", (DL_FUNC) &_BTF_rcpp_fabp_lin_reg, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_BTF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
