# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BTF <- function(TensorList, MatrixType, U0, V0, R0, SS0, Mu0, S, SaveDir, Thin, Burn, Start) {
    .Call('_BTF_BTF', PACKAGE = 'BTF', TensorList, MatrixType, U0, V0, R0, SS0, Mu0, S, SaveDir, Thin, Burn, Start)
}

EM <- function(TensorList, MatrixType, U0, V0, R0, SS0, Mu0, S) {
    .Call('_BTF_EM', PACKAGE = 'BTF', TensorList, MatrixType, U0, V0, R0, SS0, Mu0, S)
}

rcpp_fabp_lin_reg <- function(Y0, S0, opt_tau, opt_psi, R0, U0, V0, PermIndx) {
    .Call('_BTF_rcpp_fabp_lin_reg', PACKAGE = 'BTF', Y0, S0, opt_tau, opt_psi, R0, U0, V0, PermIndx)
}

