# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BTF <- function(TensorList, MatrixType, U0, V0, R0, SS0, Mu0, S, SaveDir, Thin, Burn, Start) {
    .Call('_BTF_BTF', PACKAGE = 'BTF', TensorList, MatrixType, U0, V0, R0, SS0, Mu0, S, SaveDir, Thin, Burn, Start)
}

